### PR TITLE
Pin auto-zoom to data

### PR DESCRIPTION
**Pull request by baspeti**
@ryanbaumann , I'm pretty sure that background image of the auto zoom pin control is not pretty enough. Could you provide images for pinned and unpinned states?

And could you please have a look and tell is it how you expected in overall?

### CODE REVIEW

**Comment by ryanbaumann** [comment]
Functionally, this is excellent @baspeti.  Dropping images here to show how it looks

Map will auto-zoom when data updates:


Map is `pinned`, and will not auto-zoom when data updates:


# Functionality requests

- @baspeti is it easy to add a popup tooltip when the user mouses over the icon, with the text `auto-zoom on/off`

# Design

The current design looks pretty reasonable to indicate `zooming` being enabled or disabled - any thoughts or suggestions @samanpwbb ?

**Comment by baspeti** [comment]
Fixes #74

**Comment by baspeti** [comment]
@ryanbaumann, yes, adding tooltip is easy. You can check it out now. You should see something like this:
image

**Comment by ryanbaumann** [comment]
Tooltip on the button looks great @baspeti.  I'll see if we can get suggestions on the icon - in the meantime, can we just `darken` the `off` position of the autozoom button with CSS to make it very clear that the icon is toggled off?

**Comment by baspeti** [comment]
@ryanbaumann, I tried "darkening" the background color of the `off` position, but it looked more like "disabled" to me that way.
image


If I had to decide I would go with some sort of "colorish" background like this:
image


But of course I'm not a designer. How do you fell about it?

**Comment by baspeti** [comment]
Or we could use the Power BI yellow colour:
image

Maybe this solution has the most harmony on the dashboard.

**Comment by ryanbaumann** [comment]
Thanks for trying these designs out @baspeti.  I agree that the yellow looks the best in the context of the editor, however, it won't looks good in a standalone dashboard with a different color design than the Power BI color scheme.  

I'd say we stick with the slightly darker grey option for now, and I can open a design ticket to review this separately.  Mere away!

**Pull request merged**
